[build]
  command = "npm run build --workspace svd-ambalaj-frontend"
  publish = "svd-ambalaj/svd-ambalaj-frontend/.next"

[build.environment]
  NEXT_PUBLIC_API_URL = "/.netlify/functions/api"

[functions]
  directory = "../svd-ambalaj-backend/netlify/functions"
  node_bundler = "esbuild"
  included_files = [
    "../svd-ambalaj-backend/data/**"
  ]

[[plugins]]
  package = "@netlify/plugin-nextjs"
